name: Build LaTeX

on:
  push:
    branches:
      - main 
    paths: 
      - 'report/**'
  workflow_dispatch:
  
jobs:
  build_latex:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          latexmk_shell_escape: true
          working_directory: ./report

      - name: Move PDF to root
        run: mv ./report/main.pdf ./Report.pdf

      - name: Release PDF
        uses: softprops/action-gh-release@v2
        with:
          files: ./Report.pdf