name: Build (g++)

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
        
    - name: Setup C/C++ Compiler
      id: setup-compiler
      uses: rlalik/setup-cpp-compiler@master
      with:
        compiler: gcc-latest
    
    - name: Verify GCC Installation
      run: |
        gcc --version
        g++ --version

    - name: Compile
      run: |
        g++ main.cpp src/*.cpp -o sort
